WEBSOCKET ws://{{websockethost}}/ws
Content-Type: application-json // Used for content highlighting only

// Request body, for example:
{
  "message": "First message sent on connection"
}
=== wait-for-server
{
  "message": "Send this after the server response"
}
